#!/usr/bin/env node
//
// Generates every fixture and asserts the OUTPUT is sound.
//
// Flarops writes YAML, HCL and shell out of JavaScript template literals, and
// every hazard that carries - an unescaped ${}, a block interpolated at the
// wrong indent, a key rendered with no value - produces a file that looks
// plausible and fails at the user's `werf converge`. Nothing caught those
// before this: `npm test` was the npm placeholder.
//
// The checks below need no dependencies. helm and python3 are used for deeper
// validation when present and skipped with a note when not, so the suite still
// says something useful on a bare machine.

const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');
const { generate } = require('./harness');
const { capture, firstDifference } = require('./snapshot');

const FIXTURES = path.join(__dirname, 'fixtures');
const SNAPSHOTS = path.join(__dirname, 'snapshots');
// Re-bless with `npm test -- --update`. Read the diff it produces before
// committing it: the whole point of the snapshot is that a change to generated
// output is a decision, not a side effect.
const UPDATE = process.argv.includes('--update');
let failures = 0;
let checks = 0;

function check(name, condition, detail) {
  checks++;
  if (condition) return true;
  failures++;
  console.log(`    FAIL  ${name}`);
  if (detail) console.log(`          ${String(detail).split('\n').slice(0, 6).join('\n          ')}`);
  return false;
}

function have(bin) {
  try { execFileSync('sh', ['-c', `command -v ${bin}`], { stdio: 'ignore' }); return true; }
  catch (e) { return false; }
}

const HAS_HELM = have('helm');
const HAS_PY = have('python3');

// --- checks that need nothing but Node -------------------------------------

// A "${" surviving into generated output means a JS template literal was
// escaped wrong - the value is the literal text instead of what it stood for.
function noUnexpandedJs(dir, rel) {
  const text = fs.readFileSync(path.join(dir, rel), 'utf8');
  // Helm's own {{ }} and shell's ${VAR} are legitimate; a bare ${identifier}
  // that is not inside {{ }} and not a shell expansion is not distinguishable
  // by regex alone, so look for the specific shapes that only a mistake
  // produces: "${'" (a nested-quote escape) and "undefined"/"[object Object]".
  const bad = [];
  if (/\$\{'/.test(text)) bad.push("nested-quote interpolation");
  if (/\bundefined\b/.test(text)) bad.push("literal 'undefined'");
  if (/\[object Object\]/.test(text)) bad.push("stringified object");
  return bad;
}

// values.yaml is generated by string concatenation, so a duplicated top-level
// key is a real possibility and YAML would silently keep the last one.
function duplicateTopLevelKeys(dir) {
  const text = fs.readFileSync(path.join(dir, 'deploy/helm/values.yaml'), 'utf8');
  const seen = new Map();
  for (const line of text.split('\n')) {
    const m = line.match(/^([A-Za-z_][A-Za-z0-9_]*):/);
    if (m) seen.set(m[1], (seen.get(m[1]) || 0) + 1);
  }
  return [...seen.entries()].filter(([, n]) => n > 1).map(([k]) => k);
}

// Every key a workload mounts as a secretKeyRef must be one CI actually puts
// in the Secret, or the pod sits in CreateContainerConfigError.
function secretRefsWithoutSource(dir) {
  const templatesDir = path.join(dir, 'deploy/helm/templates');
  const wf = fs.readFileSync(path.join(dir, '.github/workflows/deploy.yml'), 'utf8');
  const provided = new Set([...wf.matchAll(/SECRET_ENV_([A-Z0-9_]+):/g)].map(m => m[1]));
  provided.add('DB_PASSWORD'); // carried by its own SECRET_DB_PASSWORD line
  const missing = new Set();
  for (const file of fs.readdirSync(templatesDir)) {
    if (!file.endsWith('.yaml')) continue;
    const text = fs.readFileSync(path.join(templatesDir, file), 'utf8');
    for (const m of text.matchAll(/secretKeyRef:\s*\n\s*name:[^\n]*\n\s*key:\s*([A-Za-z0-9_]+)/g)) {
      if (!provided.has(m[1])) missing.add(`${file}: ${m[1]}`);
    }
  }
  return [...missing];
}

// --- optional, deeper ------------------------------------------------------

function helmRenders(dir) {
  const chart = path.join(dir, 'deploy/helm');
  const values = JSON.parse(fs.readFileSync(path.join(dir, '.flarops-test-values.json'), 'utf8'));
  const tmp = path.join(dir, '.ci-values.json');
  fs.writeFileSync(tmp, JSON.stringify(values));
  try {
    execFileSync('helm', ['template', 't', chart, '-f', tmp], { stdio: 'pipe' });
    execFileSync('helm', ['lint', chart, '-f', tmp], { stdio: 'pipe' });
    return null;
  } catch (e) {
    return (e.stderr || e.stdout || Buffer.from('')).toString();
  }
}

// Builds the values file CI would write: one image per werf image, plus the
// secrets the generated workflow says it passes.
function writeTestValues(dir) {
  const werf = fs.readFileSync(path.join(dir, 'werf.yaml'), 'utf8');
  const images = {};
  for (const m of werf.matchAll(/^image:\s*(\S+)\s*$/gm)) images[m[1]] = 'example.test/img:test';
  const wf = fs.readFileSync(path.join(dir, '.github/workflows/deploy.yml'), 'utf8');
  const env = {};
  for (const m of wf.matchAll(/SECRET_ENV_([A-Z0-9_]+):/g)) env[m[1]] = 'test-value';
  fs.writeFileSync(path.join(dir, '.flarops-test-values.json'), JSON.stringify({
    werf: { env: 'production', image: images },
    env,
    database: { password: 'test-value' },
  }));
}

function yamlParses(dir, rel) {
  try {
    execFileSync('python3', ['-c',
      'import sys,yaml; list(yaml.safe_load_all(open(sys.argv[1])))', path.join(dir, rel)],
      { stdio: 'pipe' });
    return null;
  } catch (e) { return (e.stderr || Buffer.from('')).toString(); }
}

function shellParses(dir, rel) {
  try {
    const extract = `
import sys, yaml, subprocess
d = yaml.safe_load(open(sys.argv[1]))
bad = []
for job in (d.get('jobs') or {}).values():
    for st in job.get('steps') or []:
        run = st.get('run')
        if not run: continue
        p = subprocess.run(['bash','-n'], input=run, text=True, capture_output=True)
        if p.returncode: bad.append(st.get('name','?') + ': ' + p.stderr.strip().split('\\n')[0])
print('\\n'.join(bad))
`;
    const out = execFileSync('python3', ['-c', extract, path.join(dir, rel)], { stdio: 'pipe' }).toString().trim();
    return out || null;
  } catch (e) { return (e.stderr || Buffer.from('')).toString(); }
}

// --- runner ----------------------------------------------------------------

(async () => {
  const names = fs.readdirSync(FIXTURES).filter(n => fs.statSync(path.join(FIXTURES, n)).isDirectory()).sort();
  console.log(`Generating ${names.length} fixture(s)` +
    `${HAS_HELM ? '' : ' (helm not found - chart rendering skipped)'}` +
    `${HAS_PY ? '' : ' (python3 not found - YAML/shell checks skipped)'}`);

  for (const name of names) {
    console.log(`\n  ${name}`);
    const result = await generate(path.join(FIXTURES, name));
    if (!check('generates without throwing', result.ok, result.error && result.error.stack)) continue;

    const expect = ['deploy/helm/values.yaml', 'deploy/.env', 'werf.yaml',
      '.github/workflows/deploy.yml', '.github/workflows/pr-capsule.yml'];
    for (const rel of expect) {
      check(`writes ${rel}`, fs.existsSync(path.join(result.dir, rel)));
    }
    if (!fs.existsSync(path.join(result.dir, 'deploy/helm/values.yaml'))) continue;

    for (const rel of ['deploy/helm/values.yaml', 'werf.yaml', '.github/workflows/deploy.yml']) {
      const bad = noUnexpandedJs(result.dir, rel);
      check(`${rel} has no unexpanded interpolation`, bad.length === 0, bad.join(', '));
    }

    const dups = duplicateTopLevelKeys(result.dir);
    check('values.yaml has no duplicate top-level keys', dups.length === 0, dups.join(', '));

    const orphanRefs = secretRefsWithoutSource(result.dir);
    check('every secretKeyRef has a key CI provides', orphanRefs.length === 0, orphanRefs.join('\n'));

    if (HAS_PY) {
      for (const rel of ['deploy/helm/values.yaml', '.github/workflows/deploy.yml', '.github/workflows/pr-capsule.yml']) {
        check(`${rel} parses as YAML`, yamlParses(result.dir, rel) === null, yamlParses(result.dir, rel));
      }
      for (const rel of ['.github/workflows/deploy.yml', '.github/workflows/pr-capsule.yml']) {
        const bad = shellParses(result.dir, rel);
        check(`${rel} run blocks pass bash -n`, !bad, bad);
      }
    }

    // Taken before the helm checks below, which write their own values files
    // into the generated tree.
    const snapPath = path.join(SNAPSHOTS, `${name}.snap`);
    const actual = capture(result.dir);
    if (UPDATE) {
      fs.mkdirSync(SNAPSHOTS, { recursive: true });
      const changed = !fs.existsSync(snapPath) || fs.readFileSync(snapPath, 'utf8') !== actual;
      fs.writeFileSync(snapPath, actual);
      console.log(`    ${changed ? 'UPDATED' : 'unchanged'}  snapshot`);
    } else if (!fs.existsSync(snapPath)) {
      check('output matches snapshot', false, `no snapshot yet - run: npm test -- --update`);
    } else {
      const diff = firstDifference(fs.readFileSync(snapPath, 'utf8'), actual);
      check('output matches snapshot', diff === null, diff);
    }

    if (HAS_HELM) {
      writeTestValues(result.dir);
      const err = helmRenders(result.dir);
      check('chart renders and lints', err === null, err);
    }

    fs.rmSync(result.parent, { recursive: true, force: true });
  }

  console.log(`\n${checks - failures}/${checks} checks passed`);
  if (failures > 0) { console.log(`${failures} FAILED`); process.exit(1); }
})().catch(e => { console.error(e); process.exit(1); });
