// Writing YAML by hand, safely.
//
// Values here come straight out of the scanned repository, so they can hold a
// quote, a backslash or a newline. Interpolating them raw produced broken (or
// attacker-shaped) YAML - the HCL side already had hclEscapeString for exactly
// this, the YAML side did not. A double-quoted YAML scalar takes the same
// escapes as JSON, so this is the full set that matters here.
const { LOOPBACK_HOST_REGEX } = require('./constants');

function yamlEscapeDoubleQuoted(value) {
  return String(value)
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\r/g, '\\r')
    .replace(/\n/g, '\\n')
    .replace(/\t/g, '\\t');
}

// `context.hasLocalhostWarnings` is set when any value still points at this
// machine, which inside a cluster is the container itself rather than the
// service that was meant - the caller reports it once at the end.
//
// The check used to be a substring search for "localhost", so 127.0.0.1,
// 0.0.0.0 and a subdomain like "db.localhost" went unmarked - the same value
// in a different spelling.
function generateEnvString(envObj, context, indent = '    ') {
  if (Object.keys(envObj).length === 0) return `${indent}# KEY: "VALUE"`;
  return Object.entries(envObj).map(([k, v]) => {
    let line = `${indent}${k}: "${yamlEscapeDoubleQuoted(v)}"`;
    if (LOOPBACK_HOST_REGEX.test(String(v))) {
      context.hasLocalhostWarnings = true;
      // Points at flarops.yaml, not here: this file is regenerated by
      // `flarops sync`, so an edit made in it does not survive.
      line += ` # Points at this container - set the right address in flarops.yaml`;
    }
    return line;
  }).join('\n');
}

module.exports = { yamlEscapeDoubleQuoted, generateEnvString };
